// <auto-generated />
using System;
using CarvedRock.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarvedRock.Api.Migrations
{
    [DbContext(typeof(CarvedRockDbContext))]
    [Migration("20210928211048_added-ProductReview")]
    partial class addedProductReview
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarvedRock.Api.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("IntroducedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoFileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Use these sturdy shoes to pass any mountain range with ease.",
                            IntroducedAt = new DateTimeOffset(new DateTime(2021, 8, 28, 22, 10, 46, 678, DateTimeKind.Unspecified).AddTicks(5502), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Mountain Walkers",
                            PhotoFileName = "shutterstock_66842440.jpg",
                            Price = 219.5m,
                            Rating = 4,
                            Stock = 12,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "For your everyday marches in the army.",
                            IntroducedAt = new DateTimeOffset(new DateTime(2021, 8, 28, 22, 10, 46, 690, DateTimeKind.Unspecified).AddTicks(3823), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Army Slippers",
                            PhotoFileName = "shutterstock_222721876.jpg",
                            Price = 125.9m,
                            Rating = 3,
                            Stock = 56,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "This backpack can survive any tornado.",
                            IntroducedAt = new DateTimeOffset(new DateTime(2021, 8, 28, 22, 10, 46, 690, DateTimeKind.Unspecified).AddTicks(4040), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Backpack Deluxe",
                            PhotoFileName = "shutterstock_6170527.jpg",
                            Price = 199.99m,
                            Rating = 5,
                            Stock = 66,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Anything you need to climb the mount Everest.",
                            IntroducedAt = new DateTimeOffset(new DateTime(2021, 8, 28, 22, 10, 46, 690, DateTimeKind.Unspecified).AddTicks(4072), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Climbing Kit",
                            PhotoFileName = "shutterstock_48040747.jpg",
                            Price = 299.5m,
                            Rating = 5,
                            Stock = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Simply the fastest kayak on earth and beyond for 2 persons.",
                            IntroducedAt = new DateTimeOffset(new DateTime(2021, 8, 28, 22, 10, 46, 690, DateTimeKind.Unspecified).AddTicks(4136), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Blue Racer",
                            PhotoFileName = "shutterstock_441989509.jpg",
                            Price = 350m,
                            Rating = 5,
                            Stock = 8,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "One person kayak with hyper boost button.",
                            IntroducedAt = new DateTimeOffset(new DateTime(2021, 8, 28, 22, 10, 46, 690, DateTimeKind.Unspecified).AddTicks(4157), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Orange Demon",
                            PhotoFileName = "shutterstock_495259978.jpg",
                            Price = 450m,
                            Rating = 2,
                            Stock = 1,
                            Type = 2
                        });
                });

            modelBuilder.Entity("CarvedRock.Api.Data.Entities.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 2,
                            Review = "It makes me feel like a real solider",
                            Title = "Very Good"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 4,
                            Review = "I climbed many mountains with this kit and it saved me many times. Definitely worth it.",
                            Title = "Handy Dandy"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 6,
                            Review = "It's not orange enough, didn't like it",
                            Title = "Orange? more like yellow"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 5,
                            Review = "Drives very fast, recommend it to anyone",
                            Title = "Very Speedy"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            Review = "I can fill it up thousands of things and these still room for more. Amazing!",
                            Title = "Very useful"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 1,
                            Review = "Leaves my feet cold and bruised. Soles fly right off.",
                            Title = "Terrible"
                        });
                });

            modelBuilder.Entity("CarvedRock.Api.Data.Entities.ProductReview", b =>
                {
                    b.HasOne("CarvedRock.Api.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
